/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/*
Lilibeth Blandon
CSC 295
ASSIGNMENT 2
*/
package Problem2;

import javax.swing.JOptionPane;
import static javax.swing.JOptionPane.INFORMATION_MESSAGE;

/**
 *
 * @author lblandon4
 */
public class PizzaFrame extends javax.swing.JFrame {

    private String onions = "";
    private String mushrooms = "";
    private String beef = "";
    private String size = "";
    
    /**
     * Creates new form PizzaFrame
     */
    public PizzaFrame() {
        initComponents();
        invisibleButton.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        topping1 = new javax.swing.JCheckBox();
        topping2 = new javax.swing.JCheckBox();
        topping3 = new javax.swing.JCheckBox();
        size1 = new javax.swing.JRadioButton();
        size2 = new javax.swing.JRadioButton();
        size3 = new javax.swing.JRadioButton();
        submit = new javax.swing.JButton();
        reset = new javax.swing.JButton();
        close = new javax.swing.JButton();
        invisibleButton = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        topping1.setText("Onions");
        topping1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                topping1ActionPerformed(evt);
            }
        });

        topping2.setText("Mushrooms");

        topping3.setText("Beef");

        size1.setText("small");

        size2.setText("medium");

        size3.setText("large");

        submit.setText("submit");
        submit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitActionPerformed(evt);
            }
        });

        reset.setText("reset");
        reset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetActionPerformed(evt);
            }
        });

        close.setText("close");
        close.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeActionPerformed(evt);
            }
        });

        invisibleButton.setText("jRadioButton1");
        invisibleButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                invisibleButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(topping1)
                    .addComponent(size1)
                    .addComponent(submit))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 65, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(topping2)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(reset)
                                .addComponent(size2)))
                        .addGap(57, 57, 57)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(topping3)
                            .addComponent(size3))
                        .addGap(47, 47, 47))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(close)
                        .addGap(31, 31, 31))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(invisibleButton)
                .addGap(153, 153, 153))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(68, 68, 68)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(topping1)
                    .addComponent(topping2)
                    .addComponent(topping3))
                .addGap(58, 58, 58)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(size1)
                    .addComponent(size2)
                    .addComponent(size3))
                .addGap(53, 53, 53)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(submit)
                    .addComponent(reset)
                    .addComponent(close))
                .addGap(18, 18, 18)
                .addComponent(invisibleButton)
                .addContainerGap(11, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void topping1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_topping1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_topping1ActionPerformed

    private void submitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitActionPerformed
        //Toppings
        if(topping1.isSelected())
        {
            onions = "onions";
        }
        if(topping2.isSelected())
        {
            mushrooms = "mushrooms";
        }
        if(topping3.isSelected())
        {
            beef = "beef";
        }
        //SIZES
        if(size1.isSelected())
        {
            size = "small";
        }
        else if(size2.isSelected())
        {
            size = "medium";
        }
        else if(size3.isSelected())
        {
            size = "large";
        }
        JOptionPane.showMessageDialog(null, "Your toppings for your " + size + " pizza are: " + onions + ", " + mushrooms + ", " + beef, "Pizza Order", INFORMATION_MESSAGE);
    }//GEN-LAST:event_submitActionPerformed

    private void resetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetActionPerformed
        topping1.setSelected(false);
        onions = "";
        topping2.setSelected(false);
        mushrooms = "";
        topping3.setSelected(false);
        beef = "";
        size1.setSelected(false);        
        size2.setSelected(false);
        size3.setSelected(false);
        size = "";
        invisibleButton.setSelected(true);
        
    }//GEN-LAST:event_resetActionPerformed

    private void invisibleButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_invisibleButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_invisibleButtonActionPerformed

    private void closeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeActionPerformed
       System.exit(0);
    }//GEN-LAST:event_closeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PizzaFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PizzaFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PizzaFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PizzaFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PizzaFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton close;
    private javax.swing.JRadioButton invisibleButton;
    private javax.swing.JButton reset;
    private javax.swing.JRadioButton size1;
    private javax.swing.JRadioButton size2;
    private javax.swing.JRadioButton size3;
    private javax.swing.JButton submit;
    private javax.swing.JCheckBox topping1;
    private javax.swing.JCheckBox topping2;
    private javax.swing.JCheckBox topping3;
    // End of variables declaration//GEN-END:variables
}
