/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Problem2;

import java.util.ArrayList;
import javax.swing.JOptionPane;

/*
    Lilibeth Blandon
    CSC292-01
    Project 1: Problem 2
    About: Checkout window is when the customer is done purchasing and then logs its information
    Class: CheckOutWindow.java
*/
/**
 *
 * @author lily
 */
public class CheckOutWindow extends javax.swing.JFrame {

    /**
     * Creates new form CheckOutWindow
     */
    
    private String totalCost;
    private int currentCustomerNumber=0;
    private int modifiedCustomerNumber;
    private ShoppingCartWindow s;
    private ArrayList<Customer> customer = new ArrayList<Customer>();
    private Customer modifyCustomer;
    private boolean modified;
    
    public CheckOutWindow() {
        initComponents();
    }
    
    public CheckOutWindow(String totalCost, ShoppingCartWindow s, int currentCustomerNumber, ArrayList<Customer> customer) {
        initComponents();
        this.totalCost = totalCost;
        this.s = s;
        this.currentCustomerNumber = currentCustomerNumber;
        this.customer = customer;
    }
    
    public CheckOutWindow(Customer modifyCustomer, int currentCustomerNumber, ArrayList<Customer> customer, ShoppingCartWindow s) {
        initComponents();
        modified = true;
        this.modifyCustomer = modifyCustomer;
        this.currentCustomerNumber = currentCustomerNumber;
        this.customer = customer;
        
        //Display info
        if(modifyCustomer.getTitle().equals("Mr")) {
            Mr_jRadioButton1.setSelected(true);
        }
        else if(modifyCustomer.getTitle().equals("Mrs")) {
            Mrs_jRadioButton2.setSelected(true);
        }
        else if(modifyCustomer.getTitle().equals("Miss")) {
            Miss_jRadioButton3.setSelected(true);
        }
        firstName_jTextField1.setText(modifyCustomer.getfName());
        lastName_jTextField2.setText(modifyCustomer.getlName());
        address1_jTextField3.setText(modifyCustomer.getAddress1());
        address2_jTextField5.setText(modifyCustomer.getAddress2());
        city_jTextField4.setText(modifyCustomer.getCity());
        if(modifyCustomer.getState().equalsIgnoreCase("Alabama"))
        {
            state_jComboBox1.setSelectedIndex(0);
        }
        else if(modifyCustomer.getState().equalsIgnoreCase("Alaska"))
        {
            state_jComboBox1.setSelectedIndex(1);
        }
        else if(modifyCustomer.getState().equalsIgnoreCase("Arizona"))
        {
            state_jComboBox1.setSelectedIndex(2);
        }
        else if(modifyCustomer.getState().equalsIgnoreCase("Arkansas"))
        {
            state_jComboBox1.setSelectedIndex(3);
        }
        else if(modifyCustomer.getState().equalsIgnoreCase("California"))
        {
            state_jComboBox1.setSelectedIndex(4);
        }
        postCode_jTextField6.setText(modifyCustomer.getPostCode());
        visa_jPasswordField1.setText(modifyCustomer.getVisaNumber());
        modifiedCustomerNumber = modifyCustomer.getOrderNumber();
        this.s = s;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        Mr_jRadioButton1 = new javax.swing.JRadioButton();
        Mrs_jRadioButton2 = new javax.swing.JRadioButton();
        Miss_jRadioButton3 = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        firstName_jTextField1 = new javax.swing.JTextField();
        lastName_jTextField2 = new javax.swing.JTextField();
        address1_jTextField3 = new javax.swing.JTextField();
        city_jTextField4 = new javax.swing.JTextField();
        address2_jTextField5 = new javax.swing.JTextField();
        postCode_jTextField6 = new javax.swing.JTextField();
        state_jComboBox1 = new javax.swing.JComboBox<>();
        visa_jPasswordField1 = new javax.swing.JPasswordField();
        cancel_jButton1 = new javax.swing.JButton();
        submit_jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        buttonGroup1.add(Mr_jRadioButton1);
        Mr_jRadioButton1.setText("Mr");

        buttonGroup1.add(Mrs_jRadioButton2);
        Mrs_jRadioButton2.setText("Mrs");

        buttonGroup1.add(Miss_jRadioButton3);
        Miss_jRadioButton3.setText("Miss");

        jLabel1.setText("Title");

        jLabel2.setText("First Name:");

        jLabel3.setText("Last Name:");

        jLabel4.setText("Address1:");

        jLabel5.setText("Address 2:");

        jLabel6.setText("City:");

        jLabel7.setText("State:");

        jLabel8.setText("PostCode:");

        jLabel9.setText("Visa:");

        state_jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Alabama", "Alaska", "Arizona", "Arkansas", "California" }));
        state_jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                state_jComboBox1ActionPerformed(evt);
            }
        });

        cancel_jButton1.setText("Cancel");
        cancel_jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancel_jButton1ActionPerformed(evt);
            }
        });

        submit_jButton2.setText("Submit");
        submit_jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submit_jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(31, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(33, 33, 33)
                                .addComponent(Mr_jRadioButton1)
                                .addGap(38, 38, 38)
                                .addComponent(Mrs_jRadioButton2)
                                .addGap(44, 44, 44)
                                .addComponent(Miss_jRadioButton3))
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(firstName_jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel9)
                            .addComponent(jLabel8)
                            .addComponent(jLabel7)
                            .addComponent(jLabel6)
                            .addComponent(jLabel5)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(city_jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lastName_jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(address1_jTextField3)
                            .addComponent(address2_jTextField5)
                            .addComponent(state_jComboBox1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(postCode_jTextField6, javax.swing.GroupLayout.DEFAULT_SIZE, 155, Short.MAX_VALUE)
                            .addComponent(visa_jPasswordField1, javax.swing.GroupLayout.DEFAULT_SIZE, 273, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(cancel_jButton1)
                        .addGap(28, 28, 28)
                        .addComponent(submit_jButton2)
                        .addGap(63, 63, 63)))
                .addGap(78, 78, 78))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Mr_jRadioButton1)
                    .addComponent(Mrs_jRadioButton2)
                    .addComponent(Miss_jRadioButton3)
                    .addComponent(jLabel1))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(firstName_jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(lastName_jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(address1_jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(address2_jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(city_jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(state_jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(postCode_jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(visa_jPasswordField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cancel_jButton1)
                    .addComponent(submit_jButton2))
                .addContainerGap(27, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cancel_jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancel_jButton1ActionPerformed
       this.dispose();
    }//GEN-LAST:event_cancel_jButton1ActionPerformed

    
    private void submit_jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submit_jButton2ActionPerformed
        if(modified == true){
            //Get changed info
            String t = "";
            if(Mr_jRadioButton1.isSelected())
            {
                t = "Mr";
            }
            else if(Mrs_jRadioButton2.isSelected())
            {
                t = "Mrs";
            }
            else if(Miss_jRadioButton3.isSelected())
            {
                t = "Miss";
            }
            String f = firstName_jTextField1.getText();
            String l = lastName_jTextField2.getText();
            String a1 = address1_jTextField3.getText();
            String a2 = address2_jTextField5.getText();
            String c = city_jTextField4.getText();
            String state = state_jComboBox1.getSelectedItem().toString();
            String p = postCode_jTextField6.getText();
            String v = visa_jPasswordField1.getText();

            Customer temp = new Customer(t,f,l,a1,a2,c,state,p,v,modifyCustomer.getTotalCost(), modifyCustomer.getOrderNumber());
            //System.out.println("debug" + modifiedCustomerNumber);
            customer.set(modifiedCustomerNumber, temp);
           // System.out.println(currentCustomerNumber);
            JOptionPane.showMessageDialog(null, "Order (Number = "+(modifiedCustomerNumber)+") has been updated successfully", "Order Info", JOptionPane.INFORMATION_MESSAGE);
            s.saveModifiedArrayList(customer);
            this.dispose();
        }
        else
        {
            if(Mr_jRadioButton1.isSelected())
            {
                customer.add(new Customer("Mr", firstName_jTextField1.getText(), lastName_jTextField2.getText(),
                                                 address1_jTextField3.getText(), address2_jTextField5.getText(), city_jTextField4.getText(),
                                                 state_jComboBox1.getSelectedItem().toString(), postCode_jTextField6.getText(),
                                                 visa_jPasswordField1.getText(), totalCost, currentCustomerNumber
                                                 ));
                currentCustomerNumber++;
            }
            else if(Mrs_jRadioButton2.isSelected())
            {
                customer.add(new Customer("Mrs", firstName_jTextField1.getText(), lastName_jTextField2.getText(),
                                                 address1_jTextField3.getText(), address2_jTextField5.getText(), city_jTextField4.getText(),
                                                 state_jComboBox1.getSelectedItem().toString(), postCode_jTextField6.getText(),
                                                 visa_jPasswordField1.getText(), totalCost, currentCustomerNumber
                                                 ));
                currentCustomerNumber++;
            }
            else if(Miss_jRadioButton3.isSelected())
            {
                customer.add(new Customer("Miss", firstName_jTextField1.getText(), lastName_jTextField2.getText(),
                                                 address1_jTextField3.getText(), address2_jTextField5.getText(), city_jTextField4.getText(),
                                                 state_jComboBox1.getSelectedItem().toString(), postCode_jTextField6.getText(),
                                                 visa_jPasswordField1.getText(), totalCost, currentCustomerNumber
                                                 ));
                currentCustomerNumber++;
            }
            else
            {
                customer.add(new Customer("", firstName_jTextField1.getText(), lastName_jTextField2.getText(),
                                                 address1_jTextField3.getText(), address2_jTextField5.getText(), city_jTextField4.getText(),
                                                 state_jComboBox1.getSelectedItem().toString(), postCode_jTextField6.getText(),
                                                 visa_jPasswordField1.getText(), totalCost, currentCustomerNumber
                                                 ));
                currentCustomerNumber++;
            }

           // System.out.println(currentCustomerNumber);
            JOptionPane.showMessageDialog(null, "Order (Number = "+(customer.size()-1)+") has been created successfully", "Order Info", JOptionPane.INFORMATION_MESSAGE);
            s.saveArrayList(customer, currentCustomerNumber);
            this.dispose();     
        }
    }//GEN-LAST:event_submit_jButton2ActionPerformed

    private void state_jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_state_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_state_jComboBox1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CheckOutWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CheckOutWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CheckOutWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CheckOutWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CheckOutWindow().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton Miss_jRadioButton3;
    private javax.swing.JRadioButton Mr_jRadioButton1;
    private javax.swing.JRadioButton Mrs_jRadioButton2;
    private javax.swing.JTextField address1_jTextField3;
    private javax.swing.JTextField address2_jTextField5;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton cancel_jButton1;
    private javax.swing.JTextField city_jTextField4;
    private javax.swing.JTextField firstName_jTextField1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField lastName_jTextField2;
    private javax.swing.JTextField postCode_jTextField6;
    private javax.swing.JComboBox<String> state_jComboBox1;
    private javax.swing.JButton submit_jButton2;
    private javax.swing.JPasswordField visa_jPasswordField1;
    // End of variables declaration//GEN-END:variables
}
